# Generated by Django 6.0.3 on 2026-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_open',
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
